// @ts-nocheck
const firebaseConfig = {
    apiKey: "AIzaSyC9mUCpTqouOX61Uiz4ndmDuLmeSS4PdFI",
    authDomain: "gamekatarnolima.firebaseapp.com",
    projectId: "gamekatarnolima",
    storageBucket: "gamekatarnolima.firebasestorage.app",
    messagingSenderId: "376669209366",
    appId: "1:376669209366:web:3bf93d2e8186a61be30637",
    measurementId: "G-KPW1XBXLJ3",
    databaseURL: "https://gamekatarnolima-default-rtdb.asia-southeast1.firebasedatabase.app"
};
if (typeof firebase!== "undefined" &&!firebase.apps.length) firebase.initializeApp(firebaseConfig);
const db = typeof firebase!== "undefined"? firebase.database() : null;
const DEV_PIN = "060117";
const questions = [
    { question: "Danau vulkanik terbesar di Indonesia sekaligus di Asia Tenggara adalah...", answers: [{ text: "Danau Toba", correct: true }, { text: "Danau Maninjau", correct: false }, { text: "Danau Singkarak", correct: false }, { text: "Danau Sentani", correct: false }] },
    { question: "Ibu kota dari negara Jepang adalah...", answers: [{ text: "Kyoto", correct: false }, { text: "Osaka", correct: false }, { text: "Tokyo", correct: true }, { text: "Sapporo", correct: false }] },
    { question: "Planet terbesar dalam tata surya kita adalah...", answers: [{ text: "Mars", correct: false }, { text: "Jupiter", correct: true }, { text: "Saturnus", correct: false }, { text: "Bumi", correct: false }] },
    { question: "Siapakah penemu bola lampu pijar yang terkenal?", answers: [{ text: "Alexander Graham Bell", correct: false }, { text: "Nikola Tesla", correct: false }, { text: "Thomas Alva Edison", correct: true }, { text: "Albert Einstein", correct: false }] },
    { question: "Mata uang resmi yang digunakan oleh negara Inggris adalah...", answers: [{ text: "Euro", correct: false }, { text: "Pound Sterling", correct: true }, { text: "Dollar", correct: false }, { text: "Yen", correct: false }] },
    { question: "Hewan mamalia terbesar di bumi saat ini adalah...", answers: [{ text: "Gajah Afrika", correct: false }, { text: "Paus Biru", correct: true }, { text: "Jerapah", correct: false }, { text: "Hiu Paus", correct: false }] },
    { question: "Monumen Nasional (Monas) terletak di kota...", answers: [{ text: "Bandung", correct: false }, { text: "Surabaya", correct: false }, { text: "Jakarta", correct: true }, { text: "Yogyakarta", correct: false }] },
    { question: "Unsur kimia dengan simbol 'O' adalah...", answers: [{ text: "Emas", correct: false }, { text: "Oksigen", correct: true }, { text: "Ozon", correct: false }, { text: "Osmium", correct: false }] },
    { question: "Candi Borobudur terletak di provinsi...", answers: [{ text: "Jawa Tengah", correct: true }, { text: "Jawa Timur", correct: false }, { text: "Jawa Barat", correct: false }, { text: "DI Yogyakarta", correct: false }] },
    { question: "Benua terkecil di dunia adalah...", answers: [{ text: "Eropa", correct: false }, { text: "Antarktika", correct: false }, { text: "Australia", correct: true }, { text: "Amerika Selatan", correct: false }] },
    { question: "Siapakah pencipta lagu Indonesia Raya?", answers: [{ text: "Ismail Marzuki", correct: false }, { text: "W.R. Soepratman", correct: true }, { text: "C. Simanjuntak", correct: false }, { text: "Kusbini", correct: false }] },
    { question: "Pegunungan tertinggi di dunia adalah...", answers: [{ text: "Pegunungan Himalaya", correct: true }, { text: "Pegunungan Andes", correct: false }, { text: "Pegunungan Alpen", correct: false }, { text: "Pegunungan Rocky", correct: false }] },
    { question: "Negara yang memiliki julukan 'Negeri Kincir Angin' adalah...", answers: [{ text: "Jerman", correct: false }, { text: "Belanda", correct: true }, { text: "Prancis", correct: false }, { text: "Swiss", correct: false }] },
    { question: "Alat untuk mengukur gempa bumi disebut...", answers: [{ text: "Termometer", correct: false }, { text: "Barometer", correct: false }, { text: "Seismograf", correct: true }, { text: "Anemometer", correct: false }] },
    { question: "Mata uang resmi Arab Saudi adalah...", answers: [{ text: "Dinar", correct: false }, { text: "Dirham", correct: false }, { text: "Riyal", correct: true }, { text: "Rupee", correct: false }] },
    { question: "Suku asli yang mendiami benua Australia adalah...", answers: [{ text: "Suku Maori", correct: false }, { text: "Suku Aborigin", correct: true }, { text: "Suku Maya", correct: false }, { text: "Suku Inka", correct: false }] },
    { question: "Siapakah penemu pesawat terbang pertama?", answers: [{ text: "Wright Bersaudara", correct: true }, { text: "Graham Bell", correct: false }, { text: "James Watt", correct: false }, { text: "Guglielmo Marconi", correct: false }] },
    { question: "Samudra terluas di bumi adalah...", answers: [{ text: "Samudra Atlantik", correct: false }, { text: "Samudra Hindia", correct: false }, { text: "Samudra Pasifik", correct: true }, { text: "Samudra Arktik", correct: false }] },
    { question: "Lagu daerah 'Anju Ahu' berasal dari...", answers: [{ text: "Sumatra Utara", correct: true }, { text: "Sumatra Barat", correct: false }, { text: "Aceh", correct: false }, { text: "Riau", correct: false }] },
    { question: "Organisasi kesehatan dunia di bawah PBB adalah...", answers: [{ text: "UNICEF", correct: false }, { text: "UNESCO", correct: false }, { text: "WHO", correct: true }, { text: "ILO", correct: false }] }
];
let shuffledQuestions = [], currentQuestionIndex = 0, score = 0, lives = 3, timePerQuestion = 10, timeLeft = 10, isLifelineUsed = false, isSoundEnabled = true, currentPlayerName = "", selectedRating = 5, timerInterval, audioCtx = null, bgmInterval, bgmStep = 0;
function initAudio() { if (!audioCtx) { const AC = window.AudioContext || window.webkitAudioContext; if (AC) audioCtx = new AC(); } if (audioCtx && audioCtx.state === "suspended") audioCtx.resume(); }
function playSound(freq, type, duration, vol = 0.1) { if (!isSoundEnabled ||!audioCtx) return; try { const osc = audioCtx.createOscillator(); const gain = audioCtx.createGain(); osc.type = type; osc.frequency.value = freq; gain.gain.setValueAtTime(vol, audioCtx.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, audioCtx.currentTime + duration); osc.connect(gain); gain.connect(audioCtx.destination); osc.start(); osc.stop(audioCtx.currentTime + duration); } catch (e) {} }
function startBGM() { stopBGM(); if (!isSoundEnabled) return; const notes = [261.63, 329.63, 392.00, 523.25, 392.00, 329.63]; bgmStep = 0; bgmInterval = setInterval(() => { if (!isSoundEnabled) return; playSound(notes[bgmStep % notes.length], "triangle", 0.25, 0.03); bgmStep++; }, 400); }
function stopBGM() { if (bgmInterval) clearInterval(bgmInterval); }
function playCorrectSound() { playSound(587.33, "sine", 0.15, 0.1); setTimeout(() => playSound(880, "sine", 0.3, 0.1), 100); }
function playWrongSound() { playSound(150, "sawtooth", 0.3, 0.1); }
function playGameOverSound() { playSound(200, "sawtooth", 0.2, 0.1); setTimeout(() => playSound(150, "sawtooth", 0.2, 0.1), 200); setTimeout(() => playSound(100, "sawtooth", 0.4, 0.1), 400); }
function shuffleArray(array) { return [...array].sort(() => Math.random() - 0.5); }
function triggerShake() { const c = document.getElementById("quiz-card"); if (c) { c.classList.remove("shake"); void c.offsetWidth; c.classList.add("shake"); } }
function triggerSlideIn() { const q = document.getElementById("quiz-box"); if (q) { q.classList.remove("slide-in"); void q.offsetWidth; q.classList.add("slide-in"); } }
function launchConfetti() { const cont = document.getElementById("confetti-container"); if (!cont) return; cont.innerHTML = ""; const colors = ["#ff4d4d", "#ffcc00", "#28a745", "#4da6ff", "#b533ff"]; for (let i = 0; i < 50; i++) { const cf = document.createElement("div"); cf.classList.add("confetti"); cf.style.left = Math.random() * 100 + "vw"; cf.style.backgroundColor = colors[Math.floor(Math.random() * colors.length)]; cf.style.animationDuration = (Math.random() * 2 + 1.5) + "s"; cont.appendChild(cf); } setTimeout(() => { cont.innerHTML = ""; }, 4000); }
function listenToLeaderboard() { const list = document.getElementById("leaderboard-list"); if (!list ||!db) return; db.ref("leaderboard").orderByChild("score").limitToLast(10).on("value", (snap) => { const scores = []; snap.forEach((child) => { scores.push(child.val()); }); scores.reverse(); if (scores.length === 0) { list.innerHTML = "<li>Belum ada rekor pemain.</li>"; return; } list.innerHTML = ""; scores.forEach((item, index) => { const li = document.createElement("li"); li.innerHTML = `<span><span class="player-rank">#${index + 1}</span> ${item.name}</span> <strong>${item.score} Poin</strong>`; list.appendChild(li); }); }); }
function saveScoreToLeaderboard(name, newScore) { if (!db) return; const userKey = name.toLowerCase().replace(/[^a-z0-9]/g, "_"); const userRef = db.ref("leaderboard/" + userKey); userRef.once("value").then((snapshot) => { if (snapshot.exists()) { const oldScore = snapshot.val().score || 0; if (newScore > oldScore) userRef.set({ name: name, score: newScore }); } else { userRef.set({ name: name, score: newScore }); } }); }
function listenToUpdateLog() { if (!db) return; db.ref("updateLog").on("value", (snapshot) => { const log = snapshot.val() || "Versi 1.0 — Game Kuis resmi dirilis!"; const el = document.getElementById("update-log-text"); const inp = document.getElementById("update-input"); if (el) el.innerText = log; if (inp) inp.value = log; }); }
function listenToTotalPlayCount() { if (!db) return; db.ref("totalPlayCount").on("value", (snapshot) => { const total = snapshot.val() || 0; const el = document.getElementById("global-play-count"); if (el) el.innerText = total.toString(); }); }
function submitFeedbackToFirebase(name, rating, text) { if (!db) return; db.ref("reviews").push({ name: name, rating: rating, text: text, timestamp: Date.now() }); }
function listenToReviews() { const list = document.getElementById("dev-reviews-list"); if (!list ||!db) return; db.ref("reviews").on("value", (snapshot) => { if (!snapshot.exists()) { list.innerHTML = "<li>Belum ada saran masuk.</li>"; return; } list.innerHTML = ""; snapshot.forEach((child) => { const item = child.val(); const li = document.createElement("li"); let stars = "★".repeat(item.rating); li.innerHTML = `<strong>${item.name}</strong> (${stars}): <br><em>"${item.text}"</em>`; list.appendChild(li); }); }); }
function prepareStartScreen() { const savedName = localStorage.getItem("quizLockedNickname"); const welcome = document.getElementById("welcome-player-text"); const box = document.getElementById("name-input-box"); if (savedName) { currentPlayerName = savedName; if (welcome) welcome.innerText = `Halo, ${savedName}! 👋`; if (box) box.classList.add("hide"); } else { if (welcome) welcome.innerText = `Pemain Baru`; if (box) box.classList.remove("hide"); } }
function selectDifficulty(mode) { const savedName = localStorage.getItem("quizLockedNickname"); const input = document.getElementById("player-name-input"); if (!savedName) { const inputVal = input? input.value.trim() : ""; if (inputVal === "") { alert("Harap masukkan nickname!"); return; } localStorage.setItem("quizLockedNickname", inputVal); currentPlayerName = inputVal; } else { currentPlayerName = savedName; } if (mode === "easy") timePerQuestion = 15; else if (mode === "medium") timePerQuestion = 10; else if (mode === "hard") timePerQuestion = 5; let playCount = parseInt(localStorage.getItem("quizPlayCount") || "0") + 1; localStorage.setItem("quizPlayCount", playCount.toString()); if (db) db.ref("totalPlayCount").transaction((current) => (current || 0) + 1); startQuiz(); }
function hideAllScreens() { ["landing-page","start-screen","settings-screen","donate-screen","dev-screen","header-info","progress-container","quiz-box","result-box"].forEach(id => { const el = document.getElementById(id); if (el) el.classList.add("hide"); }); }
function showLandingPage() { stopBGM(); hideAllScreens(); const el = document.getElementById("landing-page"); if (el) el.classList.remove("hide"); }
function startQuiz() { initAudio(); shuffledQuestions = shuffleArray([...questions]).slice(0, 10); currentQuestionIndex = 0; score = 0; lives = 3; isLifelineUsed = false; const lifeline = document.getElementById("lifeline-btn"); if (lifeline) { lifeline.disabled = false; lifeline.innerText = "💡 50:50"; } hideAllScreens(); document.getElementById("header-info")?.classList.remove("hide"); document.getElementById("progress-container")?.classList.remove("hide"); document.getElementById("quiz-box")?.classList.remove("hide"); startBGM(); showQuestion(); }
function showQuestion() { resetState(); triggerSlideIn(); updateLivesDisplay(); updateProgressBar(); startTimer(); let currentQuestion = shuffledQuestions[currentQuestionIndex]; document.getElementById("question").innerText = currentQuestion.question; document.getElementById("question-count").innerText = `Soal ${currentQuestionIndex + 1} dari ${shuffledQuestions.length}`; document.getElementById("score-count").innerText = `Skor: ${score}`; let shuffledAnswers = shuffleArray([...currentQuestion.answers]); const ansEl = document.getElementById("answer-buttons"); shuffledAnswers.forEach(answer => { const button = document.createElement("button"); button.innerText = answer.text; button.classList.add("btn"); if (answer.correct) button.dataset.correct = "true"; button.addEventListener("click", () => selectAnswer(button)); if (ansEl) ansEl.appendChild(button); }); }
function updateProgressBar() { const bar = document.getElementById("progress-bar"); if (bar) { let p = (currentQuestionIndex / shuffledQuestions.length) * 100; bar.style.width = `${p}%`; } }
function resetState() { clearInterval(timerInterval); const ans = document.getElementById("answer-buttons"); while (ans && ans.firstChild) ans.removeChild(ans.firstChild); }
function startTimer() { timeLeft = timePerQuestion; const td = document.getElementById("timer-display"); if (td) td.innerText = `⏱️ ${timeLeft}s`; timerInterval = setInterval(() => { timeLeft--; if (td) td.innerText = `⏱️ ${timeLeft}s`; if (timeLeft <= 0) { clearInterval(timerInterval); handleTimeout(); } }, 1000); }
function handleTimeout() { lives--; playWrongSound(); triggerShake(); updateLivesDisplay(); highlightCorrectAnswer(); setTimeout(() => nextQuestionOrFinish(), 1200); }
function updateLivesDisplay() { let hearts = ""; for (let i = 0; i < lives; i++) hearts += "❤️"; const el = document.getElementById("lives-display"); if (el) el.innerText = lives > 0? `Nyawa: ${hearts}` : "Nyawa: 💔"; }
function selectAnswer(selectedBtn) { clearInterval(timerInterval); const isCorrect = selectedBtn.dataset.correct === "true"; if (isCorrect) { selectedBtn.classList.add("correct"); score += 10; playCorrectSound(); } else { selectedBtn.classList.add("wrong"); lives--; playWrongSound(); triggerShake(); updateLivesDisplay(); } highlightCorrectAnswer(); setTimeout(() => nextQuestionOrFinish(), 1200); }
function useLifeline() { const ansEl = document.getElementById("answer-buttons"); if (isLifelineUsed ||!ansEl) return; isLifelineUsed = true; const btn = document.getElementById("lifeline-btn"); if (btn) { btn.disabled = true; btn.innerText = "💡 Terpakai"; } const buttons = Array.from(ansEl.children); const wrongButtons = buttons.filter(b => b.dataset.correct!== "true"); const shuffledWrong = shuffleArray(wrongButtons); for (let i = 0; i < Math.min(2, shuffledWrong.length); i++) shuffledWrong[i].style.visibility = "hidden"; }
function highlightCorrectAnswer() { const ansEl = document.getElementById("answer-buttons"); if (ansEl) { Array.from(ansEl.children).forEach(button => { if (button.dataset.correct === "true") button.classList.add("correct"); button.disabled = true; }); } }
function nextQuestionOrFinish() { currentQuestionIndex++; if (lives > 0 && currentQuestionIndex < shuffledQuestions.length) showQuestion(); else showResult(); }
function showResult() { clearInterval(timerInterval); stopBGM(); hideAllScreens(); document.getElementById("result-box")?.classList.remove("hide"); saveScoreToLeaderboard(currentPlayerName, score); if (lives === 0) playGameOverSound(); else launchConfetti(); const finalEl = document.getElementById("final-score"); if (finalEl) finalEl.innerText = lives === 0? `Game Over, ${currentPlayerName}! Skor: ${score}` : `Selamat ${currentPlayerName}! Skor ${score}!`; const highEl = document.getElementById("high-score-display"); if (highEl) highEl.innerText = `Skor disimpan di Global!`; let playCount = parseInt(localStorage.getItem("quizPlayCount") || "0"); const fb = document.getElementById("feedback-section"); if (playCount >= 3 && fb) fb.classList.remove("hide"); else if (fb) fb.classList.add("hide"); }
function addClickEvent(id, handler) { const el = document.getElementById(id); if (el) el.addEventListener("click", handler); }
document.addEventListener("DOMContentLoaded", () => {
    addClickEvent("btn-start-game", () => { initAudio(); hideAllScreens(); prepareStartScreen(); document.getElementById("start-screen")?.classList.remove("hide"); });
    addClickEvent("btn-open-settings", () => { initAudio(); hideAllScreens(); document.getElementById("settings-screen")?.classList.remove("hide"); });
    addClickEvent("btn-open-donate", () => { hideAllScreens(); document.getElementById("donate-screen")?.classList.remove("hide"); });
    document.querySelectorAll(".star").forEach(star => { star.addEventListener("click", (e) => { selectedRating = parseInt(e.target.dataset.value || "5"); document.querySelectorAll(".star").forEach(s => { if (parseInt(s.dataset.value || "0") <= selectedRating) s.classList.add("active"); else s.classList.remove("active"); }); }); });
    addClickEvent("btn-submit-feedback", () => { const t = document.getElementById("feedback-text"); const text = t? t.value.trim() : ""; if (text === "") { alert("Tulis saran dulu."); return; } submitFeedbackToFirebase(currentPlayerName, selectedRating, text); alert("Terima kasih!"); document.getElementById("feedback-section")?.classList.add("hide"); });
    addClickEvent("btn-open-dev", () => { const pin = prompt("Masukkan PIN Developer:"); if (pin === DEV_PIN) { hideAllScreens(); document.getElementById("dev-screen")?.classList.remove("hide"); listenToReviews(); listenToTotalPlayCount(); } else if (pin!== null) { alert("PIN Salah!"); } });
    addClickEvent("btn-reset-scores", () => { if (confirm("Hapus SEMUA skor online?") && db) { db.ref("leaderboard").remove(); alert("Skor direset!"); } });
    addClickEvent("btn-reset-reviews", () => { if (confirm("Hapus semua ulasan?") && db) { db.ref("reviews").remove(); alert("Ulasan direset!"); } });
    addClickEvent("btn-save-update", () => { if (!db) { alert("DB belum terhubung!"); return; } const inp = document.getElementById("update-input"); const log = inp? inp.value.trim() : ""; if (log === "") { alert("Kotak kosong!"); return; } db.ref("updateLog").set(log).then(() => alert("Update tersimpan!")).catch((e) => alert("Error: " + e.message)); });
    addClickEvent("btn-toggle-sound", () => { isSoundEnabled =!isSoundEnabled; if (!isSoundEnabled) stopBGM(); const b = document.getElementById("btn-toggle-sound"); if (b) { b.innerText = isSoundEnabled? "🔊 ON" : "🔇 OFF"; b.style.backgroundColor = isSoundEnabled? "#28a745" : "#dc3545"; } });
    addClickEvent("btn-back-from-diff", showLandingPage); addClickEvent("btn-back-from-settings", showLandingPage); addClickEvent("btn-back-from-donate", showLandingPage); addClickEvent("btn-back-from-dev", showLandingPage); addClickEvent("restart-btn", showLandingPage);
    addClickEvent("btn-easy", () => selectDifficulty("easy")); addClickEvent("btn-medium", () => selectDifficulty("medium")); addClickEvent("btn-hard", () => selectDifficulty("hard"));
    document.getElementById("lifeline-btn")?.addEventListener("click", useLifeline);
    listenToLeaderboard(); listenToUpdateLog(); showLandingPage();
});
